#variable aws_access_key {}
#variable aws_secret_key {}
variable aws_region {}
variable cidr_block {}
variable environment {}
variable vpc_name {}
variable vpc_owner {}
variable IGW_name {}
variable public_subnet1_cidr {}
variable public_subnet2_cidr {}
variable public_subnet3_cidr {}
